<?xml version ="1.0"?>
<!-- The Document Type Definition (DTD) for the file -->
<!DOCTYPE CONFIGURATION [
<!ELEMENT CONFIGURATION (SERVER, MODULE*)>
<!ELEMENT SERVER (PREF|LIST-PREF|OBJECT|LIST-OBJECT)*>
<!ELEMENT MODULE (PREF|LIST-PREF|OBJECT|LIST-OBJECT)*>
<!ATTLIST MODULE
	NAME CDATA #REQUIRED>
<!ELEMENT PREF (#PCDATA)>
<!ATTLIST PREF
	NAME CDATA #REQUIRED
	TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Float32|Float64|Bool16|Bool8|char) "char">
<!ELEMENT LIST-PREF (VALUE*)>
<!ELEMENT VALUE (#PCDATA)>
<!ATTLIST LIST-PREF
	NAME CDATA #REQUIRED
	TYPE  (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Float32|Float64|Bool16|Bool8|char) "char">
<!ELEMENT OBJECT (PREF|LIST-PREF|OBJECT|LIST-OBJECT)*>
<!ATTLIST OBJECT
	NAME CDATA #REQUIRED>
<!ELEMENT LIST-OBJECT (OBJECT-VALUE*)>
<!ELEMENT OBJECT-VALUE (PREF|LIST-PREF|OBJECT|LIST-OBJECT)*>
<!ATTLIST LIST-OBJECT
	NAME CDATA #REQUIRED>
]>
<CONFIGURATION>
	<SERVER>
		<PREF NAME="rtsp_timeout" TYPE="UInt32" >0</PREF>
		<PREF NAME="real_rtsp_timeout" TYPE="UInt32" >180</PREF>
		<PREF NAME="rtp_timeout" TYPE="UInt32" >120</PREF>
		<PREF NAME="maximum_connections" TYPE="SInt32" >1000</PREF>
		<PREF NAME="maximum_bandwidth" TYPE="SInt32" >102400</PREF>
		<PREF NAME="movie_folder" >c:\Program Files\Darwin Streaming Server\Movies\</PREF>
		<PREF NAME="bind_ip_addr" >0</PREF>
		<PREF NAME="break_on_assert" TYPE="Bool16" >false</PREF>
		<PREF NAME="auto_restart" TYPE="Bool16" >true</PREF>
		<PREF NAME="total_bytes_update" TYPE="UInt32" >1</PREF>
		<PREF NAME="average_bandwidth_update" TYPE="UInt32" >60</PREF>
		<PREF NAME="safe_play_duration" TYPE="UInt32" >600</PREF>
		<PREF NAME="module_folder" >c:\Program Files\Darwin Streaming Server\QTSSModules\</PREF>
		<PREF NAME="error_logfile_name" >Error</PREF>
		<PREF NAME="error_logfile_dir" >c:\Program Files\Darwin Streaming Server\Logs\</PREF>
		<PREF NAME="error_logfile_interval" TYPE="UInt32" >7</PREF>
		<PREF NAME="error_logfile_size" TYPE="UInt32" >256000</PREF>
		<PREF NAME="error_logfile_verbosity" TYPE="UInt32" >2</PREF>
		<PREF NAME="screen_logging" TYPE="Bool16" >true</PREF>
		<PREF NAME="error_logging" TYPE="Bool16" >true</PREF>
		<PREF NAME="drop_all_video_delay" TYPE="SInt32" >1750</PREF>
		<PREF NAME="start_thinning_delay" TYPE="SInt32" >0</PREF>
		<PREF NAME="large_window_size" TYPE="UInt32" >64</PREF>
		<PREF NAME="window_size_threshold" TYPE="UInt32" >200</PREF>
		<PREF NAME="min_tcp_buffer_size" TYPE="UInt32" >8192</PREF>
		<PREF NAME="max_tcp_buffer_size" TYPE="UInt32" >200000</PREF>
		<PREF NAME="tcp_seconds_to_buffer" TYPE="Float32" >.5</PREF>
		<PREF NAME="do_report_http_connection_ip_address" TYPE="Bool16" >false</PREF>
		<PREF NAME="default_authorization_realm" >Streaming Server</PREF>
		<PREF NAME="run_user_name" ></PREF>
		<PREF NAME="run_group_name" ></PREF>
		<PREF NAME="append_source_addr_in_transport" TYPE="Bool16" >false</PREF>
		<LIST-PREF NAME="rtsp_port" TYPE="UInt16" >
			<VALUE>554</VALUE>
			<VALUE>7070</VALUE>
			<VALUE>8000</VALUE>
			<VALUE>8001</VALUE>
		</LIST-PREF>
		<PREF NAME="max_retransmit_delay" TYPE="UInt32" >500</PREF>
		<PREF NAME="small_window_size" TYPE="UInt32" >24</PREF>
		<PREF NAME="ack_logging_enabled" TYPE="Bool16" >false</PREF>
		<PREF NAME="rtcp_poll_interval" TYPE="UInt32" >100</PREF>
		<PREF NAME="rtcp_rcv_buf_size" TYPE="UInt32" >768</PREF>
		<PREF NAME="send_interval" TYPE="UInt32" >50</PREF>
		<PREF NAME="thick_all_the_way_delay" TYPE="SInt32" >-2000</PREF>
		<PREF NAME="alt_transport_src_ipaddr" ></PREF>
		<PREF NAME="max_send_ahead_time" TYPE="UInt32" >25</PREF>
		<PREF NAME="reliable_udp_slow_start" TYPE="Bool16" >true</PREF>
		<PREF NAME="auto_delete_sdp_files" TYPE="Bool16" >false</PREF>
		<PREF NAME="authentication_scheme" >digest</PREF>
		<PREF NAME="sdp_file_delete_interval_seconds" TYPE="UInt32" >10</PREF>
		<PREF NAME="auto_start" TYPE="Bool16" >false</PREF>
		<PREF NAME="reliable_udp" TYPE="Bool16" >true</PREF>
		<PREF NAME="reliable_udp_dirs" >\</PREF>
		<PREF NAME="reliable_udp_printfs" TYPE="Bool16" >false</PREF>
		<PREF NAME="drop_all_packets_delay" TYPE="SInt32" >2500</PREF>
		<PREF NAME="thin_all_the_way_delay" TYPE="SInt32" >1500</PREF>
		<PREF NAME="always_thin_delay" TYPE="SInt32" >750</PREF>
		<PREF NAME="start_thicking_delay" TYPE="SInt32" >250</PREF>
		<PREF NAME="quality_check_interval" TYPE="UInt32" >1000</PREF>
		<PREF NAME="RTSP_error_message" TYPE="Bool16" >false</PREF>
		<PREF NAME="RTSP_debug_printfs" TYPE="Bool16" >false</PREF>
		<PREF NAME="enable_monitor_stats_file" TYPE="Bool16" >false</PREF>
		<PREF NAME="monitor_stats_file_interval_seconds" TYPE="UInt32" >10</PREF>
		<PREF NAME="monitor_stats_file_name" >server_status</PREF>
		<PREF NAME="enable_packet_header_printfs" TYPE="Bool16" >false</PREF>
		<PREF NAME="packet_header_printf_options" >rtp;rr;sr;app;ack;</PREF>
		<PREF NAME="overbuffer_rate" TYPE="Float32" >2.0</PREF>
		<PREF NAME="medium_window_size" TYPE="UInt32" >48</PREF>
		<PREF NAME="window_size_max_threshold" TYPE="UInt32" >1000</PREF>
		<PREF NAME="RTSP_server_info" TYPE="Bool16" >true</PREF>
		<PREF NAME="run_num_threads" TYPE="UInt32" >0</PREF>
		<PREF NAME="pid_file" >EasyDarwin.pid</PREF>
		<PREF NAME="force_logs_close_on_write" TYPE="Bool16" >false</PREF>
		<PREF NAME="disable_thinning" TYPE="Bool16" >false</PREF>
		<LIST-PREF NAME="player_requires_rtp_header_info" >
			<VALUE>Nokia</VALUE>
			<VALUE>Real</VALUE>
		</LIST-PREF>
		<LIST-PREF NAME="player_requires_bandwidth_adjustment" >
			<VALUE>Nokia</VALUE>
			<VALUE>Real</VALUE>
		</LIST-PREF>
		<LIST-PREF NAME="player_requires_no_pause_time_adjustment" >
			<VALUE>Nokia</VALUE>
			<VALUE>Real</VALUE>
			<VALUE>PVPlayer</VALUE>
		</LIST-PREF>
		<PREF NAME="enable_3gpp_protocol" TYPE="Bool16" >true</PREF>
		<PREF NAME="enable_3gpp_protocol_rate_adaptation" TYPE="Bool16" >true</PREF>
		<PREF NAME="3gpp_protocol_rate_adaptation_report_frequency" TYPE="UInt16" >1</PREF>
		<PREF NAME="default_stream_quality" TYPE="UInt16" >0</PREF>
		<PREF NAME="player_requires_rtp_start_time_adjust" >Real</PREF>
		<PREF NAME="enable_3gpp_debug_printfs" TYPE="Bool16" >false</PREF>
		<PREF NAME="enable_udp_monitor_stream" TYPE="Bool16" >false</PREF>
		<PREF NAME="udp_monitor_video_port" TYPE="UInt16" >5002</PREF>
		<PREF NAME="udp_monitor_audio_port" TYPE="UInt16" >5004</PREF>
		<PREF NAME="udp_monitor_dest_ip" >127.0.0.1</PREF>
		<PREF NAME="udp_monitor_src_ip" >0.0.0.0</PREF>
		<PREF NAME="enable_allow_guest_default" TYPE="Bool16" >true</PREF>
		<PREF NAME="run_num_rtsp_threads" TYPE="UInt32" >1</PREF>
		<PREF NAME="player_requires_disable_3gpp_rate_adapt" ></PREF>
		<PREF NAME="player_requires_3gpp_target_time" ></PREF>
		<PREF NAME="3gpp_target_time_milliseconds" TYPE="UInt32" >3000</PREF>
		<PREF NAME="player_requires_disable_thinning" ></PREF>
	</SERVER>
	<MODULE NAME="QTSSErrorLogModule" ></MODULE>
</CONFIGURATION>
